apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  ports:
  - port: 8080
    protocol: TCP # default 
    name: nginx # optional when only 1 port
  selector:
    app: webserver 
  type: LoadBalancer
  externalIPs:
  - 10.222.1.13
  - 10.222.1.8
