apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver1
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: webserver
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver2
spec:
  ports:
  - port: 8081
    targetPort: 80
    nodePort: 30000
  selector:
    app: webserver
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver3
spec:
  ports:
  - port: 8082
    targetPort: 80
  selector:
    app: webserver
  type: LoadBalancer
