apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: argocd-tests
  labels:
    name: web-server
    tier: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      server: web-server
      tier: testing
  template:
    spec:
      metadata:
        namespace: argocd-tests
        labels:
          server: web-server
          tier: testing
      containers:
      - name: web-server
        image: nginx
  
