apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: argocd-tests
  labels:
    server: web
    tier: testing
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: web-server
        image: nginx
  selector:
    matchLabels:
      server: web
      tier: testing
